export const ACTION_TYPES = {
  GET_BEERS_LOADING: 'GET_BEERS_LOADING',
  GET_BEERS_FETCH: 'GET_BEERS_FETCH',
  GET_BEERS_SUCCESS: 'GET_BEERS_SUCCESS',
  GET_BEERS_FAILUR: 'GET_BEERS_FAILUR',
  FETCH_SEARCH_BEER: 'FETCH_SEARCH_BEER',
  SEARCH_BEER_SUCCESS: 'SEARCH_BEER_SUCCESS',
}